services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: developer
        uid: 1000
    image: manevo-app
    container_name: manevo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - manevo-network

  db:
    image: postgres:15-alpine
    container_name: manevo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-manevo_backend}
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - manevo-network

  redis:
    image: redis:alpine
    container_name: manevo-redis
    restart: unless-stopped
    networks:
      - manevo-network

  nginx:
    image: nginx:alpine
    container_name: manevo-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - manevo-network

networks:
  manevo-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
